// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace C5.Performance.Wpf
{
    public partial class MainWindowTest
    {
[TestMethod]
[PexGeneratedBy(typeof(MainWindowTest))]
public void adder983()
{
    int i;
    i = this.adder(0, 0, (string)null);
    Assert.AreEqual<int>(0, i);
}
[TestMethod]
[PexGeneratedBy(typeof(MainWindowTest))]
public void adder922()
{
    int i;
    i = this.adder(100, 0, (string)null);
    Assert.AreEqual<int>(3, i);
}
[TestMethod]
[PexGeneratedBy(typeof(MainWindowTest))]
public void adder972()
{
    int i;
    i = this.adder(0, 0, "");
    Assert.AreEqual<int>(0, i);
}
    }
}
