// <copyright file="PexAssemblyInfo.cs">Copyright ©  2013</copyright>
// <auto-generated>
// This file should only contain assembly level attributes.
// Do not add any class or struct definitions as it may disable the ability of the tool to
// update the file.
// </auto-generated>

using System;

using Microsoft.Pex.Framework.Instrumentation;
[assembly: PexAssemblyUnderTest("C5")]
